
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD alpha
	#Range: 0 ~ 100
	invAlpha = 0
	#Toggle on by default
	byDefault = false
	#Inventory HUD vertical mode
	invVert = false
	#Inventory HUD mini mode
	invMini = true

#Settings for ArmorStatus HUD
[armorhud]
	#Show/Hide armor
	showArmor = true
	#Show item durability bar
	armBars = true
	#Show/Hide armor
	showOff = false
	#Is Armor Damage HUD enabled
	ArmorDamage = true
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Show/Hide armor
	showMain = false
	#Show/Hide armor
	showInv = false
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT, OFF
	armView = "PERCENTAGE"
	#Show/Hide empty slot icon
	showEmpty = false
	#Show/Hide armor
	showArrows = false
	#Move all items at once or each one
	moveAll = false

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = false
	#Potion HUD gap
	#Range: -5 ~ 5
	potGap = 0
	#Potion HUD mini mode
	potMini = false
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 100

#DONT TOUCH THESE FIELDS!
[positions]
	#Arrows vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	arrVal = "TOP"
	#InvIcon vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invVal = "BOTTOM"
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 20
	#OffHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	offVal = "BOTTOM"
	#Helmet vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	helmVal = "BOTTOM"
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 73
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 0
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"
	#Boots vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	bootVal = "BOTTOM"
	#Chestplate horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	chestHal = "LEFT"
	#MainHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	mainHal = "LEFT"
	#OffHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	offHal = "RIGHT"
	#InvIcon horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHal = "RIGHT"
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "BOTTOM"
	#InvIcon position (X)
	#Range: -9999 ~ 9999
	invPosX = 18
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "LEFT"
	#InvIcon position (Y)
	#Range: -9999 ~ 9999
	invPosY = 61
	#Boots horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	bootHal = "LEFT"
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = 4
	#MainHand position (X)
	#Range: -9999 ~ 9999
	mainPosX = 1
	#Chestplate vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	chestVal = "BOTTOM"
	#MainHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	mainVal = "TOP"
	#Helmet position (Y)
	#Range: -9999 ~ 9999
	helmPosY = 70
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = 150
	#Helmet position (X)
	#Range: -9999 ~ 9999
	helmPosX = 3
	#MainHand position (Y)
	#Range: -9999 ~ 9999
	mainPosY = 2
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 20
	#Chestplate position (X)
	#Range: -9999 ~ 9999
	chestPosX = 3
	#Chestplate position (Y)
	#Range: -9999 ~ 9999
	chestPosY = 53
	#Boots position (Y)
	#Range: -9999 ~ 9999
	bootPosY = 19
	#Boots position (X)
	#Range: -9999 ~ 9999
	bootPosX = 3
	#Leggings horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	legHal = "LEFT"
	#OffHand position (Y)
	#Range: -9999 ~ 9999
	offPosY = 80
	#Helmet horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	helmHal = "LEFT"
	#Arrows horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	arrHal = "LEFT"
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "TOP"
	#Arrows position (X)
	#Range: -9999 ~ 9999
	arrPosX = 1
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "MIDDLE"
	#OffHand position (X)
	#Range: -9999 ~ 9999
	offPosX = 20
	#Arrows position (Y)
	#Range: -9999 ~ 9999
	arrPosY = 20
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "LEFT"
	#Leggings position (Y)
	#Range: -9999 ~ 9999
	legPosY = 36
	#Leggings position (X)
	#Range: -9999 ~ 9999
	legPosX = 3
	#Leggings vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	legVal = "BOTTOM"

